name: Build Android CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Install maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: setup env
        run: echo PATH="$PATH":"$HOME/.maestro/bin" >> $GITHUB_ENV

      - name: maestro version
        run: maestro -v

      - name: Run emulator
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 24
          script: |
            adb install tripadvisor.apk
            maestro test ./maestro/exploring-app.yaml
